MAP = {
    "C": ".c",
    "C#": ".cs",
    "C++": ".cpp",
    "Dart": ".dart",
    "Go": ".go",
    "Java": ".java",
    "Javascript": ".js",
    "Kotlin": ".kt",
    "PHP": ".php",
    "Python": ".py",
    "Ruby": ".rb",
    "Rust": ".rs",
    "Scala": ".scala",
    "Shell": ".sh",
    "SQL": ".sql",
    "Swift": ".swift",
    "TypeScript": ".ts",
}
